 Day 01 - Numpy Introduction and all details

1. Setup & Install

In [ ]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

2. What is NumPy?

NumPy (Numerical Python) is a library for numerical computing using fast multidimensional arrays.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


3. Why Use NumPy?

Faster than Python lists and uses less memory.

In [4]:
import numpy as np

list1 = [1, 2, 3, 4]
array1 = np.array([1, 2, 3, 4])

print(array1 * 2)

[2 4 6 8]


4. Creating NumPy Arrays

In [5]:
import numpy as np

a = np.array([1, 2, 3])

b = np.zeros(5)

c = np.ones(5)

d = np.arange(1, 10)

e = np.linspace(0, 1, 5)

print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


5. NumPy Data Types

In [6]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.float64)

print(arr.dtype)

float64


6. Multi-Dimensional Arrays

In [8]:
#2D
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
#3D
arr3d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


7. Array Attributes

In [10]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


8. Indexing & Slicing

In [11]:
#Indexing
arr = np.array([10,20,30,40])

print(arr[0])
print(arr[-1])

10
40


In [12]:
#Slicing
print(arr[1:3])

[20 30]


2D Indexing